openapi: "3.0.3"
info:
  version: "3.1.0"
  title: "Digicore"
# サーバーURLを設定すると動作しなくなる ref: https://github.com/SIT-DigiCre/digicore_v3_backend/issues/226
# servers:
#   - url: "https://coreapi3.digicre.net/"
tags:
  $ref: "./tags.yml"
paths:
  $ref: "./paths.yml"
components:
  schemas:
    $ref: "./schemas.yml"
  responses:
    $ref: "./responses.yml"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
